### ISSUE TITLE
Contact form functionality, alignment

### ISSUE THREAD

**Issue by indieinc** [TigoCTM/tigoctm#17]
## Description

The contact form at the bottom of the page should function in the same manner as the form on [the Deginner website.](https://deginner.com/) Form should also be centered on the page, and the fields should match the [specifications outlined in the wiki.](https://github.com/GitGuild/tigoctm/wiki/Website-Copy#section-13)

## Tasks

- [ ] Add functionality to contact form
- [x] Center contact form on page
- [ ] Remove company field
- [ ] Ensure fields match wiki specifications

**Comment by isysd** [comment]
We can hook up to Zoho CRM just like deginner.com. @d3brouille

**Comment by isysd** [comment]
# Git Guild Bounty Program

| Total | Dev               | Sales | Reporter | Tester(s) | Maintainer | Documenter |
|--------|------------------|---------|-------------|------------|-----------------|----------------|
|N/A    | assignee(s)   | @isysd  | @indieinc | @indieinc, @d3brouille | @cindy-zimmerman | @d3brouille |
| $165 | $99 | $8.25 | $8.25 | $33 | $8.25 | $8.25 |

**Comment by d3brouille** [comment]
@isysd, does tigo have its own zoho crm account or is it sufficient to reuse deginner's for the purposes of this form for the time being?

**Comment by luisvillara** [comment]
I align the form in the center, here is the branch: https://github.com/luisvillara/tigoctm/tree/17-contact-form-functionality
