### ISSUE TITLE
Homepage text styling, cleanup

### ISSUE THREAD

**Issue by indieinc** [TigoCTM/tigoctm#21]
## Description

Some of the text remaining on the homepage needs to be formatted and styled.
The Benefits section of the homepage should be styled properly. Any lorem ipsum should be removed. Alignment, color, and spacing of all text should be checked for readability and good design.

## Tasks

- [ ] Properly style the text in the Benefits section of the homepage
- [ ] Remove lorem ipsum near bottom of homepage
- [ ] Ensure styling and design of homepage text is appealing and readable

**Comment by isysd** [comment]
# Git Guild Bounty Program

| Total | Dev               | Sales | Reporter | Tester(s) | Maintainer | Documenter |
|--------|------------------|---------|-------------|------------|-----------------|----------------|
|N/A    | assignee(s)   | @isysd  | @indieinc | @indieinc, @d3brouille | @cindy-zimmerman | @d3brouille |
| $40 | $24 | $2 | $2 | $8 | $2 | $2 |
