### ISSUE TITLE
Navigation bar

### ISSUE THREAD

**Issue by indieinc** [TigoCTM/tigoctm#22]
## Description

The other links in the navigation bar should scroll to their respective section on the homepage. The product link's behavior may depend on #19 .

The logo on the left of the navigation bar should link to the top of the homepage.

The navigation bar should float as the user scrolls down the page.

The navigation bar should be displayed across all pages of the site. Depending on #19 , there may be a Products page. If so, it should behave as (the navigation bar in the Lamassu products page)[https://lammasu.is/products/] does.

## Tasks

- [x] Remove "Navigation" link from navigation bar
- [x] Ensure each link and the navigation bar logo either scrolls to its respective section or links to the correct page
- [x] Floating navigation bar
- [x] Navigation bar persistent across site, behaves properly on each page

**Comment by isysd** [comment]
# Git Guild Bounty Program

| Total | Dev               | Sales | Reporter | Tester(s) | Maintainer | Documenter |
|--------|------------------|---------|-------------|------------|-----------------|----------------|
|N/A    | assignee(s)   | @isysd  | @indieinc | @indieinc, @d3brouille | @cindy-zimmerman | @d3brouille |
| $40 | $24 | $2 | $2 | $8 | $2 | $2 |
